<div class="loadingio-spinner-dual-ball-63b0a1oronu">
    <div class="ldio-9vvnzibl3ia">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<style type="text/css">
    @keyframes ldio-9vvnzibl3ia-o {
        0% {
            opacity: 1;
            transform: translate(0 0)
        }

        49.99% {
            opacity: 1;
            transform: translate(40px, 0)
        }

        50% {
            opacity: 0;
            transform: translate(40px, 0)
        }

        100% {
            opacity: 0;
            transform: translate(0, 0)
        }
    }

    @keyframes ldio-9vvnzibl3ia {
        0% {
            transform: translate(0, 0)
        }

        50% {
            transform: translate(40px, 0)
        }

        100% {
            transform: translate(0, 0)
        }
    }

    .ldio-9vvnzibl3ia div {
        position: absolute;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        top: 30px;
        left: 10px;
    }

    .ldio-9vvnzibl3ia div:nth-child(1) {
        background: #066cbd;
        animation: ldio-9vvnzibl3ia 1s linear infinite;
        animation-delay: -0.5s;
    }

    .ldio-9vvnzibl3ia div:nth-child(2) {
        background: #feff62;
        animation: ldio-9vvnzibl3ia 1s linear infinite;
        animation-delay: 0s;
    }

    .ldio-9vvnzibl3ia div:nth-child(3) {
        background: #066cbd;
        animation: ldio-9vvnzibl3ia-o 1s linear infinite;
        animation-delay: -0.5s;
    }

    .loadingio-spinner-dual-ball-63b0a1oronu {
        width: 50px;
        height: 50px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }

    .ldio-9vvnzibl3ia {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.5);
        backface-visibility: hidden;
        transform-origin: 0 0;
        /* see note above */
    }

    .ldio-9vvnzibl3ia div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>